# Site
name: "Yell Around"
title: "Yell Around"
description: "Yell Around for Blogging"
meta_description: "Yell Around for Blogging."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 5
baseurl: '/'
email: 'yellaround.mail@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'yellaround-salesforcelwc-in'
sharethis: '<script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=5db68f77020ee70012a2ad86&product=sticky-share-buttons"></script>'

# Authors
authors:
  Kishore:
    name: Kishore
    display_name: Kishore
    gravatar: 07fb9d10b9b6d171fa6edc6078956b4b
    email: salesforcelwc@gmail.com
    web: https://www.salesforcelwc.in
    twitter: https://twitter.com/KishoreSfdc
    description: "I am a Salesforce developer and a so-called blogger at SalesforceLwc. I love learning and sharing. SalesforceLWC aims to share relevant knowledge and scenarios for understanding Salesforce Lightning Web Components and AURA. I have also started learning the Python programming language."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

  

# Other
markdown: kramdown
highlighter: rouge
