# Site
name: "Yell Around"
title: "Yell Around"
description: "Yell Around for Blogging"
meta_description: "Yell Around for Blogging."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'yellaround.mail@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'yellaround-salesforcelwc-in'
sharethis: '<script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=5db68f77020ee70012a2ad86&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: Kishore
    display_name: Kishore
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: 
    twitter: https://twitter.com/kbandanadam
    description: "Salesforce Developer and a Blogger."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
